version: "3"
services:
 postgres:
  image: postgres
  restart: always
  container_name: postgres
  ports:
   - 5432:5432
  environment:
   - POSTGRES_USER=kong
   - POSTGRES_DB=kong
   - POSTGRES_PASSWORD=kong
 kong-ent-bootstrap:
  image: kong/kong-gateway
  container_name: kong-ent-bootstrap
  hostname: kongBootstrap
  depends_on:
   - postgres
  restart: on-failure
  command: "kong migrations bootstrap"
  environment:
   - KONG_LICENSE_DATA=$KONG_LICENSE_DATA
   - KONG_PASSWORD=KingKong
   - KONG_AUDIT_LOG=on
   - KONG_LOG_LEVEL=debug
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres
   - KONG_PG_PASSWORD=kong
 kong-ent1:
  image: kong/kong-gateway
  container_name: kong-ent1
  hostname: kongNode1
  depends_on:
   - postgres
   - kong-ent-bootstrap
  restart: always
  ports:
   - 8000:8000
   - 8001:8001
   - 8002:8002
   - 8003:8003
   - 8004:8004
   - 8443:8443
   - 8444:8444
   - 8445:8445
   - 8446:8446
   - 8447:8447
   - 9080:9080
   - 9081:9081
  environment:
#   - KONG_ENFORCE_RBAC=on
#   - KONG_ADMIN_GUI_AUTH=basic-auth
#   - KONG_ADMIN_GUI_SESSION_CONF={"secret":"secret","storage":"kong","cookie_secure":true}
#   - KONG_PASSWORD=KingKong
   - KONG_AUDIT_LOG=on
   - KONG_LOG_LEVEL=debug
   - KONG_PORTAL_GUI_HOST=localhost:8446
   - KONG_PORTAL_GUI_PROTOCOL=https
   - KONG_PORTAL_API_URL=https://localhost:8447
   - KONG_PORTAL=on
   - KONG_PORTAL_AUTH=basic-auth
   - KONG_ADMIN_GUI_URL=https://localhost:8445
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres
   - KONG_PG_PASSWORD=kong
   - KONG_LICENSE_DATA=$KONG_LICENSE_DATA
   - KONG_VITALS=on
   - KONG_PROXY_ACCESS_LOG=/dev/stdout
   - KONG_ADMIN_ACCESS_LOG=/dev/stdout
   - KONG_PROXY_ERROR_LOG=/dev/stderr
   - KONG_ADMIN_ERROR_LOG=/dev/stderr
   - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl, 0.0.0.0:9080 http2, 0.0.0.0:9081 http2 ssl
   - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
   - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8445 ssl
   - KONG_PORTAL_GUI_LISTEN=0.0.0.0:8003, 0.0.0.0:8446 ssl
   - KONG_PORTAL_API_LISTEN=0.0.0.0:8004, 0.0.0.0:8447 ssl
   - KONG_PORTAL_SESSION_CONF={"storage":"kong","cookie_name":"portal_session","secret":"super-secret","cookie_secure":true}
   - KONG_PORTAL_EMAILS_FROM=portal@apim.com
   - KONG_PORTAL_EMAILS_REPLY_TO=portal@apim.com
   - KONG_SMTP_MOCK=on
   - KONG_SSL_CERT=/etc/kong/certificates/localhost.crt
   - KONG_SSL_CERT_KEY=/etc/kong/certificates/localhost.key
   - KONG_ADMIN_SSL_CERT=/etc/kong/certificates/localhost.crt
   - KONG_ADMIN_SSL_CERT_KEY=/etc/kong/certificates/localhost.key
   - KONG_ADMIN_GUI_SSL_CERT=/etc/kong/certificates/localhost.crt
   - KONG_ADMIN_GUI_SSL_CERT_KEY=/etc/kong/certificates/localhost.key
   - KONG_PORTAL_GUI_SSL_CERT=/etc/kong/certificates/localhost.crt
   - KONG_PORTAL_GUI_SSL_CERT_KEY=/etc/kong/certificates/localhost.key
   - KONG_PORTAL_API_SSL_CERT=/etc/kong/certificates/localhost.crt
   - KONG_PORTAL_API_SSL_CERT_KEY=/etc/kong/certificates/localhost.key

  volumes:
   - ./certs/:/etc/kong/certificates:ro
