version: "3"
services:
 postgres:
  image: postgres
  restart: always
  container_name: postgres
  ports:
   - 5432:5432
  environment:
   - POSTGRES_USER=kong
   - POSTGRES_DB=kong
   - POSTGRES_PASSWORD=kong
 bootstrap:
  image: kong/kong-gateway
  container_name: bootstrap
  hostname: bootstrap
  depends_on:
   - postgres
  restart: on-failure
  command: "kong migrations bootstrap"
  environment:
   - KONG_LICENSE_DATA=$KONG_LICENSE_DATA
   - KONG_PASSWORD=KingKong
   - KONG_AUDIT_LOG=on
   - KONG_LOG_LEVEL=debug
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres
   - KONG_PG_PASSWORD=kong
 cp:
  image: kong/kong-gateway
  container_name: cp
  hostname: cp
  depends_on:
   - postgres
   - bootstrap
  restart: always
  ports:
   - 8001:8001
   - 8002:8002
   - 8003:8003
   - 8004:8004
   - 8444:8444
   - 8445:8445
   - 8446:8446
   - 8447:8447
  environment:
   - KONG_ROLE=control_plane
   - KONG_CLUSTER_CERT=/usr/local/kong/certs/cluster.crt
   - KONG_LUA_SSL_TRUSTED_CERTIFICATE=/usr/local/kong/certs/cluster.crt
   - KONG_CLUSTER_CERT_KEY=/usr/local/kong/certs/cluster.key
#   - KONG_ENFORCE_RBAC=on
#   - KONG_ADMIN_GUI_AUTH=basic-auth
#   - KONG_ADMIN_GUI_SESSION_CONF={"secret":"secret","storage":"kong","cookie_secure":false}
#   - KONG_PASSWORD=KingKong
   - KONG_AUDIT_LOG=on
   - KONG_LOG_LEVEL=debug
   - KONG_PORTAL_GUI_HOST=localhost:8003
   - KONG_PORTAL_GUI_PROTOCOL=http
   - KONG_PORTAL_API_URL=http://localhost:8004
   - KONG_PORTAL=on
   - KONG_PORTAL_AUTH=basic-auth
   - KONG_ADMIN_GUI_URL=http://localhost:8002
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres
   - KONG_PG_PASSWORD=kong
   - KONG_LICENSE_DATA=$KONG_LICENSE_DATA
   - KONG_VITALS=on
   - KONG_PROXY_ACCESS_LOG=/dev/stdout
   - KONG_ADMIN_ACCESS_LOG=/dev/stdout
   - KONG_PROXY_ERROR_LOG=/dev/stderr
   - KONG_ADMIN_ERROR_LOG=/dev/stderr
   - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
   - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8002, 0.0.0.0:8445 ssl
   - KONG_PORTAL_GUI_LISTEN=0.0.0.0:8003, 0.0.0.0:8446 ssl
   - KONG_PORTAL_API_LISTEN=0.0.0.0:8004, 0.0.0.0:8447 ssl
   - KONG_PORTAL_SESSION_CONF={"storage":"kong","cookie_name":"portal_session","secret":"super-secret","cookie_secure":false}
   - KONG_PORTAL_EMAILS_FROM=portal@apim.com
   - KONG_PORTAL_EMAILS_REPLY_TO=portal@apim.com
   - KONG_SMTP_MOCK=on
  volumes:
   - ./certs/:/usr/local/kong/certs:ro

 kong-data-plane:
  image: kong/kong-gateway
  container_name: dp
  hostname: dp
  depends_on:
   - cp
  restart: always
  ports:
   - 8000:8000
   - 8443:8443
   - 9080:9080
   - 9081:9081
  environment:
   - KONG_ROLE=data_plane
   - KONG_CLUSTER_CERT=/usr/local/kong/certs/cluster.crt
   - KONG_LUA_SSL_TRUSTED_CERTIFICATE=/usr/local/kong/certs/cluster.crt
   - KONG_CLUSTER_CERT_KEY=/usr/local/kong/certs/cluster.key
   - KONG_CLUSTER_CONTROL_PLANE=cp:8005
   - KONG_CLUSTER_TELEMETRY_ENDPOINT=cp:8006
   - KONG_PORTAL=off
   - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl, 0.0.0.0:9080 http2, 0.0.0.0:9081 http2 ssl
   - KONG_DATABASE=off
   - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
   - KONG_PROXY_ACCESS_LOG=/dev/stdout
   - KONG_ADMIN_ACCESS_LOG=/dev/stdout
   - KONG_PROXY_ERROR_LOG=/dev/stderr
   - KONG_ADMIN_ERROR_LOG=/dev/stderr
  volumes:
   - ./certs/:/usr/local/kong/certs:ro
